### ISSUE TITLE
Xinc setting error on XAMPP, WinXP: 'Cannot load pear config'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Xinc-org/xinc#207]
```
C:\xampp\php>xinc-settings set web ohloh 0

Fatal error: Uncaught exception 'Exception' with message 'Cannot load pear 
config' in C:\xampp\php\PEAR\Xinc\Ini.php:51
Stack trace:
#0 C:\xampp\php\PEAR\Xinc\Ini.php(41): Xinc_Ini->__construct()
#1 C:\xampp\php\PEAR\Xinc\Ini.php(184): Xinc_Ini::getInstance()
#2 C:\xampp\php\PEAR\Xinc\Ini.php(173): Xinc_Ini::_setSectionSetting('web', 
'ohl
oh', '0')
#3 C:\xampp\php\xinc-settings.php(29): Xinc_Ini::main()
#4 {main}
  thrown in C:\xampp\php\PEAR\Xinc\Ini.php on line 51

Can you give me some helps ?:)
```

Original issue reported on code.google.com by `tuan...@gmail.com` on 7 Jan 2010 at 9:27

**Comment by opi99** [comment]
PEAR won't be supported anymore. So issue can be closed.
